// src/pages/Terms.jsx
import React from "react";
import "./Terms.css";

export default function Terms() {
  return (
    <main className="quote-container terms-page" role="main" aria-label="Terms of Service">
      <article className="estimate-card" style={{ marginTop: 0 }}>
        <h1>Terms of Service</h1>
        <p className="muted">Last updated: 2025-08-19</p>

        {/* Table of contents */}
        <nav className="mt-16" aria-label="Table of contents">
          <ul>
            <li><a href="#services">1. Services</a></li>
            <li><a href="#quotes">2. Quotes & Pricing</a></li>
            <li><a href="#files-ip">3. Files & Intellectual Property</a></li>
            <li><a href="#technology">4. Technology, Quoting Engine & API</a></li>
            <li><a href="#acceptable-use">5. Acceptable Use</a></li>
            <li><a href="#orders">6. Orders & Lead Times</a></li>
            <li><a href="#shipping">7. Shipping, Pickup & Risk of Loss</a></li>
            <li><a href="#payment">8. Payment, Refunds & Cancellations</a></li>
            <li><a href="#warranty">9. Warranty, Quality & Limitations</a></li>
            <li><a href="#privacy">10. Privacy</a></li>
            <li><a href="#changes">11. Changes to These Terms</a></li>
            <li><a href="#law">12. Governing Law</a></li>
            <li><a href="#contact">13. Contact</a></li>
          </ul>
        </nav>

        <section id="intro" className="mt-16">
          <p>
            These Terms of Service (“Terms”) govern your use of the instant quote tool and fabrication
            services provided by <strong>Chicago 3D Printworks</strong> (“we,” “us,” “our”). By using our website or API,
            or by requesting/placing an order offline, you agree to these Terms.
          </p>
        </section>

        <section id="services" className="mt-16">
          <h3>1. Services</h3>
          <p>
            We provide on-demand 3D printing and related services based on files you upload (e.g., STL/OBJ).
            Our operators may adjust orientation, supports, or minor print settings to achieve the best results.
          </p>
        </section>

        <section id="quotes" className="mt-16">
          <h3>2. Quotes & Pricing</h3>
          <ul className="checklist">
            <li>
              Our site provides <b>instant, non-binding estimates</b> generated by our quoting engine. These estimates
              use geometric metrics (volume, surface area, triangle count, bounding box) and machine/time models
              to predict material usage and print time.
            </li>
            <li>
              Quotes are intended to help you <b>download and review pricing scenarios</b> with our account managers so we can
              explore design tweaks, materials, or batch sizes that reduce cost.
            </li>
            <li>
              Final pricing may change after a human review for printability, orientation/support strategy, scaling,
              or requested changes. Taxes, shipping, and any rush/finishing fees will be shown on your invoice.
            </li>
            <li>Unless stated otherwise, quotes are valid for 14 days.</li>
          </ul>
        </section>

        <section id="files-ip" className="mt-16">
          <h3>3. Files & Intellectual Property</h3>
          <ul className="checklist">
            <li>You represent you own or have rights to use and fabricate the uploaded models.</li>
            <li>
              You retain all IP to your models; you grant us a limited license to fabricate your order and to store
              files/metadata to operate and improve the service.
            </li>
            <li>Do not submit illegal, infringing, weapons-related, or unsafe designs.</li>
          </ul>
        </section>

        <section id="technology" className="mt-16">
          <h3>4. Technology, Quoting Engine & API</h3>
          <ul className="checklist">
            <li>
              Our instant quote tool runs a <b>custom Python quoting engine</b> that parses mesh geometry using
              libraries such as <b>trimesh</b> together with our own analyzers. It computes volume, surface area,
              triangle count, and bounding boxes, then applies <b>material profiles</b> (density, recommended layer
              heights, process multipliers) and <b>machine throughput models</b> to estimate print time and material mass.
            </li>
            <li>
              The algorithms, models, tuning parameters, UI, and API endpoints are <b>proprietary technology</b> of
              Chicago 3D Printworks and/or our licensors. You may not reverse engineer, copy, or create derivative works.
            </li>
            <li>
              Estimates are <b>engineering approximations</b>—actual results may vary with orientation, supports,
              part geometry, environmental conditions, and operator choices.
            </li>
            <li>
              API access (if provided) is limited, revocable, and subject to fair-use and security controls.
            </li>
          </ul>
        </section>

        <section id="acceptable-use" className="mt-16">
          <h3>5. Acceptable Use</h3>
          <p>
            You may not use our services to create prohibited items, violate laws/regulations, or harm others.
            We may refuse or cancel any order at our discretion.
          </p>
        </section>

        <section id="orders" className="mt-16">
          <h3>6. Orders & Lead Times</h3>
          <ul className="checklist">
            <li><b>No on-site checkout yet:</b> Orders are confirmed <i>offline</i> by invoice, email confirmation, or approved PO.</li>
            <li>Production begins after written confirmation and payment instructions are provided.</li>
            <li>Lead times are estimates and vary with queue, materials, and design complexity.</li>
            <li>
              Finish, color, and tolerances vary by process/material; functional parts may require post-processing or hardware.
            </li>
          </ul>
        </section>

        <section id="shipping" className="mt-16">
          <h3>7. Shipping, Pickup & Risk of Loss</h3>
          <ul className="checklist">
            <li>Risk of loss passes to you at pickup or when we hand the shipment to the carrier.</li>
            <li>Inspect deliveries promptly and notify us of any issues within 5 business days.</li>
          </ul>
        </section>

        <section id="payment" className="mt-16">
          <h3>8. Payment, Refunds & Cancellations</h3>
          <ul className="checklist">
            <li>
              <b>Payments are not processed through the website at this time.</b> Invoices will include payment
              instructions (e.g., card link, ACH, or other agreed method).
            </li>
            <li>Because parts are custom-made, cancellations or refunds may be limited once production starts.</li>
            <li>If a print fails due to our process, we will reprint or issue credit at our discretion.</li>
          </ul>
        </section>

        <section id="warranty" className="mt-16">
          <h3>9. Warranty, Quality & Limitations</h3>
          <ul className="checklist">
            <li>3D-printed parts can show layer lines, minor artifacts, and anisotropic properties.</li>
            <li>
              Except as required by law, services are provided “as is” without implied warranties; uptime or
              uninterrupted access to the quoting engine is not guaranteed.
            </li>
            <li>
              To the fullest extent permitted, our liability is limited to the amount you paid for the impacted order; we
              are not liable for consequential or incidental damages.
            </li>
          </ul>
        </section>

        <section id="privacy" className="mt-16">
          <h3>10. Privacy</h3>
          <p>
            We handle personal data in accordance with our Privacy Policy (available on our site). We may contact
            you about quotes, orders, and service updates.
          </p>
        </section>

        <section id="changes" className="mt-16">
          <h3>11. Changes to These Terms</h3>
          <p>
            We may update these Terms from time to time. Material changes will be posted with an updated date.
            Continued use of the service after changes constitutes acceptance.
          </p>
        </section>

        <section id="law" className="mt-16">
          <h3>12. Governing Law</h3>
          <p>
            These Terms are governed by the laws of the State of Illinois, without regard to conflict-of-law principles.
            Venue lies in the state or federal courts located in Cook County, Illinois.
          </p>
        </section>

        <section id="contact" className="mt-16">
          <h3>13. Contact</h3>
          <p>
            Questions? Email us at{" "}
            <a href="mailto:hello@chicago3dprintworks.com">hello@chicago3dprintworks.com</a>.
          </p>
        </section>

        <div className="actions" style={{ marginTop: 18 }}>
          <a className="button-secondary" href="/">Back to Home</a>
        </div>
      </article>
    </main>
  );
}
